//go:build stado_embed_binaries && darwin && amd64

// Generated by hack/fetch-binaries.go — DO NOT EDIT.
// Embedded ast-grep darwin/amd64 binary + sha256 for stado's first-use extractor.

package astgrep

import (
	_ "embed"
	"runtime"
)

//go:embed bundled/ast-grep-darwin-amd64
var bundledBytes []byte

var bundledSHA256 = "145ca9e7e66113d560250a89652e277c52fef585a7f269458c2cf957b5948847"

func isWindows() bool { return runtime.GOOS == "windows" }
