//go:build stado_embed_binaries && linux && arm64

// Generated by hack/fetch-binaries.go — DO NOT EDIT.
// Embedded ast-grep linux/arm64 binary + sha256 for stado's first-use extractor.

package astgrep

import (
	_ "embed"
	"runtime"
)

//go:embed bundled/ast-grep-linux-arm64
var bundledBytes []byte

var bundledSHA256 = "854eea1acbf2394ce8d0fd7ee5696b35338a636839cd5ef030eba792badbb410"

func isWindows() bool { return runtime.GOOS == "windows" }
