//go:build stado_embed_binaries && linux && amd64

// Generated by hack/fetch-binaries.go — DO NOT EDIT.
// Embedded ast-grep linux/amd64 binary + sha256 for stado's first-use extractor.

package astgrep

import (
	_ "embed"
	"runtime"
)

//go:embed bundled/ast-grep-linux-amd64
var bundledBytes []byte

var bundledSHA256 = "c8b72307e9943710ab9531759d1d258750b4189ba74da8d6931a6db4e279e833"

func isWindows() bool { return runtime.GOOS == "windows" }
