//go:build stado_embed_binaries && darwin && arm64

// Generated by hack/fetch-binaries.go — DO NOT EDIT.
// Embedded ast-grep darwin/arm64 binary + sha256 for stado's first-use extractor.

package astgrep

import (
	_ "embed"
	"runtime"
)

//go:embed bundled/ast-grep-darwin-arm64
var bundledBytes []byte

var bundledSHA256 = "3ee1c319af5259a25a4dbbbc5ee8b2faca7d152d078e14b29e8d765e88465b58"

func isWindows() bool { return runtime.GOOS == "windows" }
