//go:build stado_embed_binaries && windows && amd64

// Generated by hack/fetch-binaries.go — DO NOT EDIT.
// Embedded ast-grep windows/amd64 binary + sha256 for stado's first-use extractor.

package astgrep

import (
	_ "embed"
	"runtime"
)

//go:embed bundled/ast-grep-windows-amd64.exe
var bundledBytes []byte

var bundledSHA256 = "43cafc30a8f5ffdac7e26a65fdc3e2646e1959948cfb458c2723f9bb53dfbd9f"

func isWindows() bool { return runtime.GOOS == "windows" }
