//go:build stado_embed_binaries && darwin && arm64

// Generated by hack/fetch-binaries.go — DO NOT EDIT.
// Embedded rg darwin/arm64 binary + sha256 for stado's first-use extractor.

package rg

import (
	_ "embed"
	"runtime"
)

//go:embed bundled/rg-darwin-arm64
var bundledBytes []byte

var bundledSHA256 = "0e0cb83f5195f1f51bb8feef1fff5b0b171e82bd1db6bd35deee701a3e7102f8"

func isWindows() bool { return runtime.GOOS == "windows" }
