//go:build stado_embed_binaries && darwin && amd64

// Generated by hack/fetch-binaries.go — DO NOT EDIT.
// Embedded rg darwin/amd64 binary + sha256 for stado's first-use extractor.

package rg

import (
	_ "embed"
	"runtime"
)

//go:embed bundled/rg-darwin-amd64
var bundledBytes []byte

var bundledSHA256 = "923dcc25cab57d33f4e7dd0476d4b74a554401a38817e246a8d6101dcd51c50f"

func isWindows() bool { return runtime.GOOS == "windows" }
