//go:build stado_embed_binaries && windows && amd64

// Generated by hack/fetch-binaries.go — DO NOT EDIT.
// Embedded rg windows/amd64 binary + sha256 for stado's first-use extractor.

package rg

import (
	_ "embed"
	"runtime"
)

//go:embed bundled/rg-windows-amd64.exe
var bundledBytes []byte

var bundledSHA256 = "f162b54de2adfc72d78adb1dbada2dedda111ae0a5e2f6e9500f4f909664c5d2"

func isWindows() bool { return runtime.GOOS == "windows" }
