//go:build stado_embed_binaries && linux && amd64

// Generated by hack/fetch-binaries.go — DO NOT EDIT.
// Embedded rg linux/amd64 binary + sha256 for stado's first-use extractor.

package rg

import (
	_ "embed"
	"runtime"
)

//go:embed bundled/rg-linux-amd64
var bundledBytes []byte

var bundledSHA256 = "f401154e2393f9002ac77e419f9ee5521c18f4f8cd3e32293972f493ba06fce7"

func isWindows() bool { return runtime.GOOS == "windows" }
