//go:build stado_embed_binaries && linux && arm64

// Generated by hack/fetch-binaries.go — DO NOT EDIT.
// Embedded rg linux/arm64 binary + sha256 for stado's first-use extractor.

package rg

import (
	_ "embed"
	"runtime"
)

//go:embed bundled/rg-linux-arm64
var bundledBytes []byte

var bundledSHA256 = "e07d5c85fa9ca740ff4ab8bbac60a1e11c7a5ce242435f7820a03f7c20ef6276"

func isWindows() bool { return runtime.GOOS == "windows" }
