package keys

var Defaults = map[Action]string{
	AppExit:                 "ctrl+d,ctrl+x ctrl+c",
	SessionInterrupt:        "esc,ctrl+g",
	HistoryPrevious:         "up,ctrl+p",
	HistoryNext:             "down,ctrl+n",
	InputSubmit:             "enter",
	InputNewline:            "shift+enter,ctrl+j",
	InputClear:              "ctrl+c",
	InputMoveLeft:           "left,ctrl+b",
	InputMoveRight:          "right,ctrl+f",
	InputWordForward:        "alt+f,alt+right,ctrl+right",
	InputWordBackward:       "alt+b,alt+left,ctrl+left",
	InputLineHome:           "ctrl+a",
	InputLineEnd:            "ctrl+e",
	InputDeleteToLineEnd:    "ctrl+k",
	InputDeleteToLineStart:  "ctrl+u",
	InputDeleteWordForward:  "alt+d,alt+delete,ctrl+delete",
	InputDeleteWordBackward: "ctrl+w,ctrl+backspace,alt+backspace",
	InputBackspace:          "backspace",
	InputDelete:             "delete",
	MessagesPageUp:          "pageup,ctrl+alt+b",
	MessagesPageDown:        "pagedown,ctrl+alt+f",
	MessagesHalfPageUp:      "ctrl+alt+u",
	MessagesHalfPageDown:    "ctrl+alt+d",
	MessagesFirst:           "home",
	MessagesLast:            "ctrl+alt+g,end",
	CommandList:             "ctrl+p",
	AgentSwitch:             "ctrl+x a",
	ModelSwitch:             "ctrl+x m",
	SessionSwitch:           "ctrl+x l",
	SessionNew:              "ctrl+x n",
	TaskView:                "ctrl+x k",
	ThemeSwitch:             "ctrl+x t",
	StatusView:              "ctrl+x s",
	ThinkingToggle:          "ctrl+x h",
	TipsToggle:              "?",
	Approve:                 "y,enter",
	Deny:                    "n,esc",
	EditSummary:             "e",
	SidebarToggle:           "ctrl+t",
	SidebarNarrower:         "ctrl+x [",
	SidebarWider:            "ctrl+x ]",
	ToolExpand:              "shift+tab",
	ModeToggle:              "tab",
	ModeToggleBtw:           "ctrl+x ctrl+b",
	ForceQueue:              "alt+enter",
}
