package sandbox

// macOS sandbox-exec profile generator.
//
// sandbox-exec accepts a "Scheme-ish" DSL file (conventional extension
// `.sb`). This file generates one from a Policy. The resulting profile
// is textual + self-contained so we can unit-test it on any platform
// — the actual spawn lives under //go:build darwin in runner_darwin.go.
//
// Reference:
//   - `man sandbox-exec` (macOS manpage, deprecated but functional)
//   - apple/sandbox-profiles source on Apple's open-source archive
//
// Apple marks sandbox-exec as deprecated, yet every macOS release still
// ships with it. Stado uses it as the v1 path per PLAN §3.5; if Apple
// removes it we'll switch to App Sandbox's entitlements-based model.

import (
	"fmt"
	"strings"
)

// RenderSandboxProfile produces a .sb profile that:
//   - denies everything by default
//   - allows file-read* under each FSRead path
//   - allows file-read* + file-write* under each FSWrite path
//   - allows process-exec for each Exec entry
//   - allows network-outbound per NetPolicy.Kind
//
// The CWD is also always file-read*-allowed so the wrapped command
// can load its own binary + dynamic libs. Empty Policy fields expand
// to no allow-rules — the effect is a deny-default profile.
func RenderSandboxProfile(p Policy) string {
	var b strings.Builder
	b.WriteString(";; Generated by stado from a sandbox.Policy.\n")
	b.WriteString(";; Deny-default; explicit allow rules follow.\n\n")
	b.WriteString("(version 1)\n")
	b.WriteString("(deny default)\n")
	b.WriteString("(debug deny)\n\n")

	// Always allow reading the system libraries + dynamic-link machinery.
	// Without these, almost every command (including /bin/sh) fails to
	// start.
	b.WriteString(";; System libraries — needed for dyld + libc.\n")
	b.WriteString("(allow process-fork)\n")
	b.WriteString("(allow process-exec*)\n")
	b.WriteString("(allow file-read-metadata)\n")
	for _, prefix := range []string{
		"/usr/lib", "/usr/bin", "/System", "/Library/Frameworks",
		"/Library/Preferences", "/private/var/db/dyld",
	} {
		fmt.Fprintf(&b, "(allow file-read* (subpath %s))\n", sbxString(prefix))
	}
	if p.CWD != "" {
		fmt.Fprintf(&b, "(allow file-read* (subpath %s))\n", sbxString(p.CWD))
		fmt.Fprintf(&b, "(allow process-exec (subpath %s))\n", sbxString(p.CWD))
	}

	// User-declared FS read/write.
	for _, path := range p.FSRead {
		fmt.Fprintf(&b, "(allow file-read* (subpath %s))\n", sbxString(path))
	}
	for _, path := range p.FSWrite {
		fmt.Fprintf(&b, "(allow file-read* (subpath %s))\n", sbxString(path))
		fmt.Fprintf(&b, "(allow file-write* (subpath %s))\n", sbxString(path))
	}

	// Exec allow-list.
	for _, bin := range p.Exec {
		fmt.Fprintf(&b, "(allow process-exec (literal %s))\n", sbxString(bin))
	}

	// Network policy.
	b.WriteString("\n;; Network.\n")
	switch p.Net.Kind {
	case NetAllowAll:
		b.WriteString("(allow network*)\n")
	case NetDenyAll:
		// nothing — default deny remains in force
		b.WriteString(";; (net kind: deny)\n")
	case NetAllowHosts:
		for _, host := range p.Net.Hosts {
			fmt.Fprintf(&b, "(allow network-outbound (remote tcp %s))\n",
				sbxString(host+":443"))
		}
	}

	return b.String()
}

// sbxString quotes s for the sandbox-exec DSL. The grammar's string
// literals are double-quoted with backslash escapes for quote +
// backslash. Paths rarely contain either but the escape still matters
// for tests that pass odd inputs.
func sbxString(s string) string {
	var out strings.Builder
	out.WriteByte('"')
	for _, r := range s {
		switch r {
		case '"':
			out.WriteString(`\"`)
		case '\\':
			out.WriteString(`\\`)
		default:
			out.WriteRune(r)
		}
	}
	out.WriteByte('"')
	return out.String()
}
