package sandbox

// macOS sandbox-exec profile generator.
//
// sandbox-exec accepts a "Scheme-ish" DSL file (conventional extension
// `.sb`). This file generates one from a Policy. The resulting profile
// is textual + self-contained so we can unit-test it on any platform
// — the actual spawn lives under //go:build darwin in runner_darwin.go.
//
// Reference:
//   - `man sandbox-exec` (macOS manpage, deprecated but functional)
//   - apple/sandbox-profiles source on Apple's open-source archive
//
// Apple marks sandbox-exec as deprecated, yet every macOS release still
// ships with it. Stado uses it as the v1 path per PLAN §3.5; if Apple
// removes it we'll switch to App Sandbox's entitlements-based model.

import (
	"fmt"
	"os/exec"
	"strings"
)

// execLookPath is the variable form of [exec.LookPath] so tests can stub
// the resolver for host-independent assertions about the rendered
// profile. Production callers always hit the real PATH lookup.
var execLookPath = exec.LookPath

// RenderSandboxProfile produces a .sb profile that:
//   - denies everything by default
//   - allows file-read* under each FSRead path
//   - allows file-read* + file-write* under each FSWrite path
//   - allows process-exec for each Exec entry
//   - allows network-outbound per NetPolicy.Kind
//
// The CWD is also always file-read*-allowed so the wrapped command
// can load its own binary + dynamic libs. Empty Policy fields expand
// to no allow-rules — the effect is a deny-default profile.
func RenderSandboxProfile(p Policy) string {
	var b strings.Builder
	b.WriteString(";; Generated by stado from a sandbox.Policy.\n")
	b.WriteString(";; Deny-default; explicit allow rules follow.\n\n")
	b.WriteString("(version 1)\n")
	b.WriteString("(deny default)\n")
	b.WriteString("(debug deny)\n\n")

	// Always allow reading the system libraries + dynamic-link machinery.
	// Without these, almost every command (including /bin/sh) fails to
	// start.
	//
	// Exec is intentionally NOT blanket-allowed here. The original
	// `(allow process-exec*)` defeated the per-binary allow-list at the
	// bottom of this function — sandbox-exec's union semantics mean
	// `(allow process-exec*)` cannot be narrowed by adding more allow
	// rules. Callers that need to spawn /bin/sh / /usr/bin/git / etc.
	// MUST declare them in Policy.Exec; this profile's job is to
	// enforce the allow-list, not paper over policy gaps. The host
	// process retains `(allow process-fork)` so the wrapped command
	// can itself fork; only the spawn-a-new-binary capability is gated.
	b.WriteString(";; System libraries — needed for dyld + libc.\n")
	b.WriteString("(allow process-fork)\n")
	b.WriteString("(allow file-read-metadata)\n")
	for _, prefix := range []string{
		"/usr/lib", "/usr/bin", "/System", "/Library/Frameworks",
		"/Library/Preferences", "/private/var/db/dyld",
	} {
		fmt.Fprintf(&b, "(allow file-read* (subpath %s))\n", sbxString(prefix))
	}
	if p.CWD != "" {
		fmt.Fprintf(&b, "(allow file-read* (subpath %s))\n", sbxString(p.CWD))
		// Gemini deep-dive (post-v0.54.0): the prior
		// `(allow process-exec (subpath %s))` here was a sandbox
		// escape vector. A tool with `fs.write` access to the workdir
		// could drop a script or binary and execute it, completely
		// bypassing the per-binary [Policy.Exec] allow-list that the
		// loop further down emits as `(literal "<absolute>")` rules.
		// Only the binaries the operator explicitly declares in
		// Policy.Exec should be exec'able; the CWD itself stays
		// readable for dyld / source loading but not exec'able.
	}

	// User-declared FS read/write.
	for _, path := range p.FSRead {
		fmt.Fprintf(&b, "(allow file-read* (subpath %s))\n", sbxString(path))
	}
	for _, path := range p.FSWrite {
		fmt.Fprintf(&b, "(allow file-read* (subpath %s))\n", sbxString(path))
		fmt.Fprintf(&b, "(allow file-write* (subpath %s))\n", sbxString(path))
	}

	// Exec allow-list. sandbox-exec's `(literal "...")` predicate matches
	// against the ABSOLUTE path of the executed binary, not the basename.
	// [Policy.Exec] is conventionally populated with basenames (e.g.
	// `exec:git` from [internal/mcp.ParseCapabilities] yields
	// `Exec: ["git"]`) and the runner resolves via [exec.LookPath]
	// before spawning. To make the allowlist match what sandbox-exec
	// actually sees, resolve each entry here too: absolute entries pass
	// through unchanged; bare names go through [execLookPath]. A lookup
	// failure emits the entry as-given so a typo deny-fails predictably
	// (rather than silently widening the sandbox by skipping the rule).
	//
	// Symlink nuance: if the binary itself is a symlink (e.g. /bin/sh →
	// /usr/local/bin/dash), sandbox-exec's literal matches against the
	// path the kernel records for the exec, which is the symlink path
	// (not the resolved target). Resolving via LookPath gives us the
	// PATH-found symlink path, which is what the runner will also pass
	// to the child via /bin/sh-style invocation — so they line up.
	for _, bin := range p.Exec {
		resolved := bin
		if !strings.HasPrefix(bin, "/") {
			if abs, err := execLookPath(bin); err == nil {
				resolved = abs
			}
		}
		fmt.Fprintf(&b, "(allow process-exec (literal %s))\n", sbxString(resolved))
	}

	// Network policy.
	b.WriteString("\n;; Network.\n")
	switch p.Net.Kind {
	case NetAllowAll:
		b.WriteString("(allow network*)\n")
	case NetDenyAll:
		// nothing — default deny remains in force
		b.WriteString(";; (net kind: deny)\n")
	case NetAllowHosts:
		for _, host := range p.Net.Hosts {
			fmt.Fprintf(&b, "(allow network-outbound (remote tcp %s))\n",
				sbxString(host+":443"))
		}
	}

	return b.String()
}

// sbxString quotes s for the sandbox-exec DSL. The grammar's string
// literals are double-quoted with backslash escapes for quote +
// backslash. Paths rarely contain either but the escape still matters
// for tests that pass odd inputs.
func sbxString(s string) string {
	var out strings.Builder
	out.WriteByte('"')
	for _, r := range s {
		switch r {
		case '"':
			out.WriteString(`\"`)
		case '\\':
			out.WriteString(`\\`)
		default:
			out.WriteRune(r)
		}
	}
	out.WriteByte('"')
	return out.String()
}
