package plugins

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/foobarto/stado/internal/workdirpath"
)

const maxPluginLockBytes int64 = 4 << 20

// LockEntry is one row in plugin-lock.toml. EP-0039 §lock file.
type LockEntry struct {
	StoreKey       string `toml:"store_key"`       // exact source-keyed installed directory
	Identity       string `toml:"identity"`        // logical package identity, e.g. github.com/foo/bar/sub@v1.0.0
	SourceRevision string `toml:"source_revision"` // exact fetched tag/ref or full commit selector
	ResolvedCommit string `toml:"resolved_commit"` // full commit dereferenced from SourceRevision
	PackageVersion string `toml:"package_version"` // signed manifest semver, independent of a commit ref
	ManifestDigest string `toml:"manifest_digest"` // canonical signed-manifest digest
	WASMSHA256     string `toml:"wasm_sha256"`     // hex sha256 of plugin.wasm
	AnchorFpr      string `toml:"anchor_fingerprint"`
	InstalledAt    string `toml:"installed_at"` // RFC3339
}

// Lock is the in-memory representation of .stado/plugin-lock.toml.
// Mirrors go.sum semantics: reproducible installs via --from-lock.
type Lock struct {
	Entries []LockEntry
}

// NewLock returns an empty lock.
func NewLock() *Lock { return &Lock{} }

// Add inserts or updates one exact installed store row. Multiple rows may share
// a logical semver identity after an explicitly accepted tag rewrite; retaining
// the old row is required while its rollback package remains installed.
func (l *Lock) Add(e LockEntry) {
	for i, existing := range l.Entries {
		if existing.StoreKey != "" && existing.StoreKey == e.StoreKey {
			l.Entries[i] = e
			return
		}
	}
	l.Entries = append(l.Entries, e)
}

// Get returns the unique entry for identity. Rewritten identities with more
// than one exact store row are intentionally reported as ambiguous.
func (l *Lock) Get(identity string) (LockEntry, bool) {
	var found *LockEntry
	for _, e := range l.Entries {
		if e.Identity == identity {
			if found != nil {
				return LockEntry{}, false
			}
			copyEntry := e
			found = &copyEntry
		}
	}
	if found == nil {
		return LockEntry{}, false
	}
	return *found, true
}

// Write serialises the lock to path in TOML format (hand-written to
// avoid importing a TOML library just for this). EP-0039 §lock file.
func (l *Lock) Write(path string) error {
	return withPluginFileLock(path, func() error { return l.write(path) })
}

func (l *Lock) write(path string) error {
	var buf bytes.Buffer
	buf.WriteString("# stado plugin lock file — do not edit by hand\n")
	buf.WriteString("# generated by stado plugin install\n\n")
	for _, e := range l.Entries {
		buf.WriteString("[[plugin]]\n")
		fmt.Fprintf(&buf, "store_key          = %q\n", e.StoreKey)
		fmt.Fprintf(&buf, "identity           = %q\n", e.Identity)
		fmt.Fprintf(&buf, "source_revision    = %q\n", e.SourceRevision)
		fmt.Fprintf(&buf, "resolved_commit    = %q\n", e.ResolvedCommit)
		fmt.Fprintf(&buf, "package_version    = %q\n", e.PackageVersion)
		fmt.Fprintf(&buf, "manifest_digest    = %q\n", e.ManifestDigest)
		fmt.Fprintf(&buf, "wasm_sha256        = %q\n", e.WASMSHA256)
		fmt.Fprintf(&buf, "anchor_fingerprint = %q\n", e.AnchorFpr)
		fmt.Fprintf(&buf, "installed_at       = %q\n", e.InstalledAt)
		buf.WriteByte('\n')
	}
	if int64(buf.Len()) > maxPluginLockBytes {
		return fmt.Errorf("plugin lock exceeds %d bytes", maxPluginLockBytes)
	}
	root, err := workdirpath.NewUserConfigResolver().OpenRoot(filepath.Dir(path))
	if err != nil {
		return err
	}
	defer func() { _ = root.Close() }()
	return workdirpath.NewRootResolver(root).WriteFileAtomic(filepath.Base(path), buf.Bytes(), 0o644)
}

// UpdateLock serializes one complete lock-file read/modify/write transaction.
// Callers must use this instead of a separate ReadLock + Write pair.
func UpdateLock(path string, update func(*Lock) error) error {
	return withPluginFileLock(path, func() error {
		lock, err := ReadLock(path)
		if errors.Is(err, os.ErrNotExist) {
			lock = NewLock()
		} else if err != nil {
			return err
		}
		if err := update(lock); err != nil {
			return err
		}
		return lock.write(path)
	})
}

// Remove drops the entry with the exact versioned identity.
func (l *Lock) Remove(identity string) bool {
	removed := false
	kept := make([]LockEntry, 0, len(l.Entries))
	for _, entry := range l.Entries {
		if entry.Identity == identity {
			removed = true
			continue
		}
		kept = append(kept, entry)
	}
	l.Entries = kept
	return removed
}

// ReadLock parses path as a plugin-lock.toml file.
// Returns os.ErrNotExist when the file is absent.
func ReadLock(path string) (*Lock, error) {
	root, err := workdirpath.NewUserConfigResolver().OpenRoot(filepath.Dir(path))
	if err != nil {
		return nil, err
	}
	defer func() { _ = root.Close() }()
	data, err := workdirpath.NewRootResolver(root).ReadFileLimited(filepath.Base(path), maxPluginLockBytes)
	if err != nil {
		return nil, err
	}
	return parseLockTOML(data)
}

// parseLockTOML is a minimal hand-rolled parser for the lock file format
// written by Lock.Write. Only handles the subset we produce.
func parseLockTOML(data []byte) (*Lock, error) {
	l := NewLock()
	var current *LockEntry
	for _, rawLine := range bytes.Split(data, []byte("\n")) {
		line := bytes.TrimSpace(rawLine)
		if len(line) == 0 || line[0] == '#' {
			continue
		}
		if bytes.Equal(line, []byte("[[plugin]]")) {
			if current != nil {
				l.Entries = append(l.Entries, *current)
			}
			current = &LockEntry{}
			continue
		}
		if current == nil {
			continue
		}
		key, val, ok := parseKV(line)
		if !ok {
			continue
		}
		switch key {
		case "store_key":
			current.StoreKey = val
		case "identity":
			current.Identity = val
		case "source_revision":
			current.SourceRevision = val
		case "resolved_commit":
			current.ResolvedCommit = val
		case "package_version":
			current.PackageVersion = val
		case "manifest_digest":
			current.ManifestDigest = val
		case "wasm_sha256":
			current.WASMSHA256 = val
		case "anchor_fingerprint":
			current.AnchorFpr = val
		case "installed_at":
			current.InstalledAt = val
		}
	}
	if current != nil {
		l.Entries = append(l.Entries, *current)
	}
	return l, nil
}

// parseKV splits a TOML assignment line into key and unquoted string value.
func parseKV(line []byte) (key, val string, ok bool) {
	idx := bytes.IndexByte(line, '=')
	if idx < 0 {
		return "", "", false
	}
	k := string(bytes.TrimSpace(line[:idx]))
	v := bytes.TrimSpace(line[idx+1:])
	// Unquote simple double-quoted strings.
	if len(v) >= 2 && v[0] == '"' && v[len(v)-1] == '"' {
		return k, string(v[1 : len(v)-1]), true
	}
	return k, string(v), true
}

// LockEntryFromResolvedManifest records both the source ref actually fetched
// and the full commit it dereferenced to, plus the independently signed package
// version. For monorepos the source ref may be `<subdir>/vX.Y.Z`; for commit
// pins both sourceRevision and resolvedCommit are the same full SHA.
func LockEntryFromResolvedManifest(id Identity, sourceRevision, resolvedCommit string, m Manifest) (LockEntry, error) {
	digest, err := m.ManifestDigest()
	if err != nil {
		return LockEntry{}, err
	}
	record, err := NewRemoteInstallRecord(id, sourceRevision, resolvedCommit, m)
	if err != nil {
		return LockEntry{}, err
	}
	return LockEntry{
		StoreKey: record.StoreKey,
		Identity: id.Canonical(), SourceRevision: sourceRevision, ResolvedCommit: resolvedCommit,
		PackageVersion: m.Version, ManifestDigest: digest, WASMSHA256: m.WASMSHA256,
		AnchorFpr: m.AuthorPubkeyFpr, InstalledAt: time.Now().UTC().Format(time.RFC3339),
	}, nil
}
