package plugins

import (
	"bytes"
	"fmt"
	"os"
	"time"
)

// LockEntry is one row in plugin-lock.toml. EP-0039 §lock file.
type LockEntry struct {
	Identity    string `toml:"identity"`    // e.g. github.com/foo/bar@v1.0.0
	WASMSHA256  string `toml:"wasm_sha256"` // hex sha256 of plugin.wasm
	AnchorFpr   string `toml:"anchor_fingerprint"`
	InstalledAt string `toml:"installed_at"` // RFC3339
}

// Lock is the in-memory representation of .stado/plugin-lock.toml.
// Mirrors go.sum semantics: reproducible installs via --from-lock.
type Lock struct {
	Entries []LockEntry
}

// NewLock returns an empty lock.
func NewLock() *Lock { return &Lock{} }

// Add inserts or updates the entry for e.Identity (last-writer-wins).
func (l *Lock) Add(e LockEntry) {
	for i, existing := range l.Entries {
		if existing.Identity == e.Identity {
			l.Entries[i] = e
			return
		}
	}
	l.Entries = append(l.Entries, e)
}

// Get returns the entry for identity, or (zero, false).
func (l *Lock) Get(identity string) (LockEntry, bool) {
	for _, e := range l.Entries {
		if e.Identity == identity {
			return e, true
		}
	}
	return LockEntry{}, false
}

// Write serialises the lock to path in TOML format (hand-written to
// avoid importing a TOML library just for this). EP-0039 §lock file.
func (l *Lock) Write(path string) error {
	var buf bytes.Buffer
	buf.WriteString("# stado plugin lock file — do not edit by hand\n")
	buf.WriteString("# generated by stado plugin install\n\n")
	for _, e := range l.Entries {
		buf.WriteString("[[plugin]]\n")
		fmt.Fprintf(&buf, "identity           = %q\n", e.Identity)
		fmt.Fprintf(&buf, "wasm_sha256        = %q\n", e.WASMSHA256)
		fmt.Fprintf(&buf, "anchor_fingerprint = %q\n", e.AnchorFpr)
		fmt.Fprintf(&buf, "installed_at       = %q\n", e.InstalledAt)
		buf.WriteByte('\n')
	}
	return os.WriteFile(path, buf.Bytes(), 0o644)
}

// ReadLock parses path as a plugin-lock.toml file.
// Returns os.ErrNotExist when the file is absent.
func ReadLock(path string) (*Lock, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	return parseLockTOML(data)
}

// parseLockTOML is a minimal hand-rolled parser for the lock file format
// written by Lock.Write. Only handles the subset we produce.
func parseLockTOML(data []byte) (*Lock, error) {
	l := NewLock()
	var current *LockEntry
	for _, rawLine := range bytes.Split(data, []byte("\n")) {
		line := bytes.TrimSpace(rawLine)
		if len(line) == 0 || line[0] == '#' {
			continue
		}
		if bytes.Equal(line, []byte("[[plugin]]")) {
			if current != nil {
				l.Entries = append(l.Entries, *current)
			}
			current = &LockEntry{}
			continue
		}
		if current == nil {
			continue
		}
		key, val, ok := parseKV(line)
		if !ok {
			continue
		}
		switch key {
		case "identity":
			current.Identity = val
		case "wasm_sha256":
			current.WASMSHA256 = val
		case "anchor_fingerprint":
			current.AnchorFpr = val
		case "installed_at":
			current.InstalledAt = val
		}
	}
	if current != nil {
		l.Entries = append(l.Entries, *current)
	}
	return l, nil
}

// parseKV splits a TOML assignment line into key and unquoted string value.
func parseKV(line []byte) (key, val string, ok bool) {
	idx := bytes.IndexByte(line, '=')
	if idx < 0 {
		return "", "", false
	}
	k := string(bytes.TrimSpace(line[:idx]))
	v := bytes.TrimSpace(line[idx+1:])
	// Unquote simple double-quoted strings.
	if len(v) >= 2 && v[0] == '"' && v[len(v)-1] == '"' {
		return k, string(v[1 : len(v)-1]), true
	}
	return k, string(v), true
}

// LockEntryFromManifest builds a LockEntry from an installed manifest.
func LockEntryFromManifest(id Identity, m Manifest) LockEntry {
	return LockEntry{
		Identity:    id.Canonical(),
		WASMSHA256:  m.WASMSHA256,
		AnchorFpr:   m.AuthorPubkeyFpr,
		InstalledAt: time.Now().UTC().Format(time.RFC3339),
	}
}
