//go:build !stado_embed_binaries

// Default stub for the bundled ast-grep blob. Release builds pass
// `-tags stado_embed_binaries`, which drops this file and picks up the
// per-platform `bundled_<goos>_<goarch>.go` generated by
// `hack/fetch-binaries.go`.
//
// See internal/tools/rg/bundled_stub.go for the full pattern rationale.

package astgrep

import "runtime"

var bundledBytes []byte
var bundledSHA256 string

func isWindows() bool { return runtime.GOOS == "windows" }
